# Generated by Django 3.2 on 2023-02-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id'], 'verbose_name': 'Итем', 'verbose_name_plural': 'Итемы'},
        ),
    ]
